image: golang:1.6

stages:
    - setup
    - build
    - test

before_script:
    - mkdir -p /gopath/src/gitlab.com/gerardabello
    - export GOPATH=/gopath
    - cp -r ../weight/ /gopath/src/gitlab.com/gerardabello/
    - cd /gopath/src/gitlab.com/gerardabello/weight
    - go get github.com/gorilla/websocket
    - go get github.com/stretchr/testify/assert
    - go get github.com/gonum/blas
    - go get github.com/gonum/blas/blas64

build:
    stage: build
    script:
        - go install

build-tests:
    stage: build
    script:
        - go test -c -i
        - go test -c -i ./layers
        - go test -c -i ./tensor
        - go test -c -i ./debug
        - go test -c -i ./costs
        - go test -c -i ./training

test-basic:
    stage: test
    script:
        - go test -v -cover
        - go test -v -cover ./layers
        - go test -v -cover ./tensor
        - go test -v -cover ./debug
        - go test -v -cover ./costs
        - go test -v -cover ./training

test-net-accuracy:
    stage: test
    script:
        - wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz -P ./tests/mnist
        - wget http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz -P ./tests/mnist
        - wget http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz -P ./tests/mnist
        - wget http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz -P ./tests/mnist
        - go test -v -short ./tests/mnist --timeout 30m
